/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.co.fullmarks.java14;

public class Library {
    public Integer isInteger(Object o) {
        if (o instanceof Integer i) {
            return i;
        } else {
            return null;
        }
    }
}
